### ISSUE TITLE
Exception after successive image loading

### ISSUE THREAD

**Issue by astik** [natecox/angular-darkroomjs#1]
Hi,
I tried the demo, it works great =)
When I enable "save" feature like this :

```
        <nc-darkroom image="dr_ctrl.image" 
                     on-crop="dr_ctrl.image_changed(image)"
                     history="true"
                     crop="{}"
                     save="{}"
                     rotate="false"
                     save="false">
        </nc-darkroom>
```

I have a new button to save the image (by default it just destroy the darkroom context which is fine to reproduce the anomaly).

Step to reproduce the bug :
- load an image : the image is displayed
- save : darkroom context is destroy, only an img tag is remaining
- load a new image : the image is displayed, an exception occured in the console

The exception is :

```
TypeError: container.parentNode is null
...image=new Image;image.onload=function(){container.parentNode.replaceChild(image,...
```

**Comment by astik** [comment]
You can reproduce this bug without setting the "save" action in fact.
Simply load multiple time an image with the "Upload" button.

**Comment by natecox** [comment]
Can you provide a code sample to demonstrate the issue? I'm not able to replicate it, but I may simply be misunderstanding the problem.

**Comment by astik** [comment]
No need for code for reproducing :

```
git clone git@github.com:natecox/angular-darkroomjs.git
cd angular-darkroomjs/
bower install
# choose fabric#1.4.0
# open demo/index.html in a browser
# select an image with the file chooser
# select another image with the file chooser
```
- exception occurs in firefox (37) :

```
TypeError: container.parentNode is null
```

-> exception occurs in chrome (41) :

```
Uncaught TypeError: Cannot read property 'replaceChild' of null
```

Tested on OSX 10.8.4 and Ubuntu 14.04.2 LTS.

**Comment by natecox** [comment]
The `TypeError` that you're getting actually comes from darkroom. I'll figure out how to get rid of it eventually, but it doesn't affect the usage of this package.

I was able to replicate the error that you're having, but it seems to be related to ngFlow. The image upload itself isn't happening when you try to do them in quick succession; you can verify this by popping a `console.log(...)` into `load_new_image` on the demo's `app.js`.

**Comment by natecox** [comment]
Seems to be picky about the image itself too. The `flow::fileAdded` hook never gets fired off on certain images.

**Comment by astik** [comment]
I don't have any problem with file loading with Flow. Except the fact that the event isn't triggered when the image has already been  loaded, for example :
- load image 1
- load image 2
- load image 1 <- event not sent

**Comment by natecox** [comment]
Yeah, you seem to be on the right track with that. However, I'm not overly concerned with that to be honest; ngFlow is being used as a simple demonstration of how to use the darkroom directive. I'm assuming that most people will already have an upload flow and simply want this package to handle the cropping. 

When I get some free time I'll go through and update the demo to be more stable. If you've got a working solution feel free to issue a pull request for it and I can merge it in.

**Comment by astik** [comment]
To be honest, I have no other solution for now as you are the first solution I have evaluated =)
We'll stick with your solution as it get the job done nicely despite this issue.
As it is not a ng-darkroom issue, I'm closing this issue and I'll keep an eye on a potential solution =P

**Comment by natecox** [comment]
I wonder if this is a viable solution: http://stackoverflow.com/questions/23808972/how-to-set-single-file-in-ng-flow

**Comment by astik** [comment]
And it works perfectly =)

```
angular
    .module('ncDarkroomTest', ['flow', 'angular-darkroom'])
    .controller('AppCtrl', AppCtrl)
    .config(['flowFactoryProvider', function (flowFactoryProvider) {
        flowFactoryProvider.defaults = {
            singleFile: true
        };
    }]);
```

**Comment by natecox** [comment]
I've pushed updated code to the develop branch. Test it out and make sure it works.

**Comment by natecox** [comment]
Reopening this until demo is verified as fixed.

**Comment by astik** [comment]
Despite the remaining darkroom anomaly, the ngFlow modification works great and fix the scenario defined above :
- load image 1
- load image 2
- load image 1 <- event is sent

**Comment by astik** [comment]
Hi @natecox 
Any chance to have this feature merge back into the main branch ?

**Comment by natecox** [comment]
Apparently I missed the confirmation on this; master is updated and available from bower. Let me know if there's any issue with it.
