### ISSUE TITLE
Modifying image from external domains

### ISSUE THREAD

**Issue by astik** [natecox/angular-darkroomjs#2]
It will be handy to be able to access remote image for edition. For example, you media file could be on a different server than your application's one :

```
        <nc-darkroom image="'ABSOLUTE-URL-TO-A-FILE'" 
                     on-crop="dr_ctrl.image_changed(image)"
                     history="true"
                     crop="{}"
                     rotate="false"
                     save="false">
```

With an external absolute URL, you'll get this error :

```
SecurityError: The operation is insecure.
```

This is a security feature and not a bug. The browser is preventing accessing image data from external domain. It is possible to set CORS on the IMG tag to be able to work with it, by replacing :

```
angular.element(img_tag).attr('src', scope.image);
```

with something like this :

```
angular.element(img_tag).attr({
  crossOrigin : 'anonymous',
  src : scope.image
})
```

Of course, it will work only with server that enable CORS.

More informations :
- http://www.w3.org/TR/html5/scripting-1.html#security-with-canvas-elements
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Img#Attributes

**Comment by natecox** [comment]
@astik 
I can get this to work successfully with an image coming from a server that supports CORS, however on an image that does not come from a CORS enabled server Fabric fatally excepts in a way that I can't seem to track via darkroom.

I can't really release code that I know is going to cause fatal exceptions, so we need to figure out how to track that.

I've added a feature branch referenced above. Feel free to pull it down and take a stab at it. If you get success create a pull request.

**Comment by astik** [comment]
Hi @natecox, thanks for reploying quickly on this.
The cross domain issue is something we won't be able to fix on our side, it's a browser restriction and we can't do anything about that beside working with CORS.
If you say that CORS works already, i may to retry my test, sorry for the inconvenience then =/

**Comment by natecox** [comment]
@astik Try the demo on the feature branch I referenced above, I have it working with CORS enabled servers via an input box.

**Comment by astik** [comment]
I have tested the feature branch few minutes ago, works perfectly with remote server with CORS enabled.
To ease the demo, you may add an online example with CORS capability, like the one on html5 rocks : http://www.html5rocks.com/static/images/cors_flow.png =)

**Comment by astik** [comment]
I reopen the issue until you merge into the trunk and release a new version.
Thanks in advance.

**Comment by astik** [comment]
The crossOrigin attribute seems to fail the local loading. We may need to conditionnaly add this attribute regarding the image URL.

I propose something like this :

```
 imgAttrs = {
    src: scope.image
};
if (scope.image.substring(0,4) === 'http') {
    imgAttrs.crossOrigin = 'anonymous';
}
angular
    .element(img_tag)
    .attr(imgAttrs)
;
```

**Comment by natecox** [comment]
If that works it seems fine to me. 

The main issue with this right now is preventing Fabric from fatally excepting when you pass in a non-CORS enabled URL. This definitely needs to be solved before merging back in with master.

**Comment by astik** [comment]
Sure the fix is not complete, still it is a better solution than the current code as CORS request are handled correctly.
I agree that we need a better handling for non-CORS provided image.
- do we need to create a canvas, then to insert the image and to try to read from it and finally catch a potential exception ?
- does Fabric provide an API to test the ability to handle an image ?

**Comment by astik** [comment]
Hi
Any chance to have this fix into the main branch ? It is not complete, but it is still better than the actual behavior, this will narrow the faulty use case.

**Comment by natecox** [comment]
I've updated the feature branch for this with all of the new changes. Can you give it a try using the demo for me and make sure that it's working for you?

**Comment by jbouzekri** [comment]
Just tested the branch in my project and it is working. I will use my fork while waiting for this branch to be merged.

**Comment by natecox** [comment]
Feature is pushed to bower as version 0.0.6.

**Comment by natecox** [comment]
@jbouzekri let me know if you have any other issues with this; I'd really appreciate a bit more debugging in terms of the Fabric side of it.
